export enum STATUS {
  PENDING = 'PENDING',
  REVIEWED_BY_AI = 'REVIEWED_BY_AI',
  REVIEWED_BY_TEACHER = 'REVIEWED_BY_TEACHER',
  REVIEWED_BY_TEACHER_AND_AI = 'REVIEWED_BY_TEACHER_AND_AI',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
