DELETE FROM problem where id>=1;
INSERT INTO problem (task_id, title, description, image, created_at) VALUES
(2, 'Technology and Life', 'Some people say that technology has improved our lives. Do you agree or disagree with this view?', null, '2024-12-08'),
(2, 'Practical vs Academic', 'Some people believe that students should learn practical skills such as cooking and budgeting at school, while others think that academic subjects are more important. Discuss both views and give your opinion.', null, '2024-12-08'),
(2, 'Social Media Effects', 'Social media is an essential part of young people’s lives nowadays, but its impact is often criticized. What are the advantages and disadvantages of social media in teenagers’ and young adults’ lives?', null, '2024-12-08'),
(2, 'Overpopulation Issues', 'Overpopulation in many major urban centres around the world is a major problem. What are the causes of this? How can this problem be solved?', null, '2024-12-08'),
(2, 'Online Shopping Impact', 'Why do some people prefer online shopping? What impact does this have on local businesses?', null, '2024-12-08'),
(1, 'Monthly Rainfall', 'The bar chart below shows the average rainfall for Australia by month for last year. The line shows the average rainfall for Australia by month for the last 40 years.

Summarise the information by selecting and reporting the main features, and make comparisons where relevant.', 'https://www.ielts-blog.com/reports/average-rainfall-au-writing-1-test-1.jpg', '2024-12-08'),
(1, 'University Enrollment', 'The graphs below show the enrolments of overseas students and local students in Australian universities over a ten year period. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. You should write at least 150 words.', 'https://engnovatewebsitestorage.blob.core.windows.net/ielts-writing-task-1-images/e000c619b4ffffb1', '2024-12-08'),
(1, 'Population and GDP', 'The chart below shows the GDP growth per year for three countries between 2007 and 2010.
Summarize the information by selecting and reporting the main features, and make comparisons where relevant.
You should write at least 150 words.', 'https://www.ielts-mentor.com/images/writingsamples/ielts-graph-268-gdp-in-three-countries.png', '2024-12-08'),
(1, 'Energy Usage', 'The charts below show the percentage of electricity consumed by different sectors in Eastern Australia in 2007 and 2010. Summarize the information and make comparisons where relevant.', 'https://images.dolenglish.vn/rs:auto:::0/w:712/q:70/aHR0cHM6Ly9zdWlqbTljbG91b2JqLnZjZG4uY2xvdWQvUFVCTElDL01FRElBL2I5ZjlhNDBlLTg4NWEtNDU0Ny1iYmEwLWVmM2E2OThhNGE0ZC5wbmc=', '2024-12-08'),
(1, 'Recycling Process', 'The diagram below illustrate how recycled paper is made. Summarize the information by selecting and reporting the main features, and make comparison where relevant.', 'https://engnovatewebsitestorage.blob.core.windows.net/ielts-writing-task-1-images/afced03067c83137', '2024-12-08'),
(1, 'Town Development', 'The maps below show the village of Pebbleton 20 years ago and now. Summarize the information by describing the main developments and differences.', 'https://images.dolenglish.vn/rs:auto:::0/w:712/q:70/aHR0cHM6Ly9zdWlqbTljbG91b2JqLnZjZG4uY2xvdWQvUFVCTElDL01FRElBLzIwN2NiYWRhLThmNDUtNGNhMS04YzcxLWY2M2FmNzg3ZmM1NC5wbmc=', '2024-12-08'),
(1, 'Water Usage Comparison', 'The charts below show the percentage of water used for different purposes in six areas of the world. Summarize the information by integrating the data and making comparisons.', 'https://images.dolenglish.vn/rs:auto:::0/w:712/q:70/aHR0cHM6Ly9zdWlqbTljbG91b2JqLnZjZG4uY2xvdWQvUFVCTElDL01FRElBL2EwZDNhNmM0LWY2OWQtNDhiMy05MDBmLWMwNjI1YTQyN2I4ZC5wbmc=', '2024-12-08');